- hosts: localhost
  become: yes
  vars:
    vagrant_version: 2.2.5
    packages:
      - ansible
      - containerd.io
      - docker-ce
      - docker-ce-cli 
      - git
      - vagrant
      - virtualbox
  tasks:
    - name: Install aux apt packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        update_cache: yes

    - name: Add Ansible repository
      apt_repository:
        repo: "ppa:ansible/ansible"
        update_cache: yes
      when: "'ansible' in packages"

    - name: Add Docker repo key
      apt_key:
        id: 9DC858229FC7DD38854AE2D88D81803C0EBFCD88
        url: https://download.docker.com/linux/ubuntu/gpg
      when: "'docker-ce' in packages"

    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_facts['lsb']['codename']}} stable"
        update_cache: yes
      when: "'docker-ce' in packages"
    
    - name: Install packages
      apt:
        name: "{{packages}}"
        update_cache: yes
 
    - name: Install Vagrant
      apt:
        deb: "https://releases.hashicorp.com/vagrant/{{vagrant_version}}/vagrant_{{vagrant_version}}_x86_64.deb"
      when: "'vagrant' in packages"
